### PR TITLE
updated dependencies & ignored cleaning of ca-bundle/res

### PR DESCRIPTION
**Pull request by CZechBoY**

### CODE REVIEW

**Comment by JanTvrdik** [comment]
?

**Comment by CZechBoY** [comment]
:-)
Dependencies updated using composer update. Because you commit vendor directory, I updated it for you.

File vendor/composer/ca-bundle/res/cacert.pam is required for refresh-version.php script and s cleaned by dg/composer-cleaner. This PR ignores cleaning that directory.

Clear now?

**Comment by JanTvrdik** [comment]
(merged manually as da4801f94041adc9b38b26bf624547c8fafb988b)

**Comment by CZechBoY** [comment]
I think you just merged instaled.json + composer.lock but without updating vendor files :-/

**Pull request closed without merging**
